apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  selector:
    app: grpc-service
  ports:
    - protocol: TCP
      port: 50051  # External port
      targetPort: 50051  # Internal port where the app listens
  type: LoadBalancer  # Exposes the service externally
